"""Gera o protótipo estático. Execução opcional: python scripts/build.py."""
from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).resolve().parent.parent
SITE_URL = 'https://coreilabs.github.io/mef/'
OG_IMAGE = SITE_URL + 'assets/images/opengraph.png'
WA = 'https://wa.me/556191565342?text=Ol%C3%A1%2C%20vim%20pelo%20site%20e%20gostaria%20de%20mais%20informa%C3%A7%C3%B5es.'
ARROW = '<span class="arrow" aria-hidden="true">↗</span>'
SEARCH = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg>'
CHAT = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M20 11.5a8 8 0 0 1-11.6 7.2L4 20l1.3-4.4A8 8 0 1 1 20 11.5Z"/><path d="M8 8c0 4 4 7 7 7l1-2-2-1-1 1-2-2 1-1-2-2Z"/></svg>'
CATEGORIES = {'familia': 'Família', 'acolhimento': 'Acolhimento', 'bem-estar': 'Bem-estar'}
TAGS = {'escuta': 'Escuta', 'dialogo': 'Diálogo', 'apoio': 'Apoio', 'rotina': 'Rotina'}
POSTS = [
    dict(slug='escuta-que-acolhe', title='A escuta que acolhe: o primeiro passo para uma boa conversa', category='acolhimento', tags=['escuta','dialogo'], image='hands', date='2026-09-18', label='18 set. 2026', read='4 min', excerpt='Estar presente, respeitar o tempo do outro e abrir espaço para uma conversa sem julgamentos.', sections=[('Presença antes de respostas','Uma conversa pode começar com uma pergunta simples e tempo para ouvir. Em vez de preparar uma resposta enquanto a outra pessoa fala, podemos prestar atenção ao que ela deseja compartilhar.'),('Cada pessoa tem seu próprio tempo','Nem sempre é fácil colocar uma experiência em palavras. Respeitar uma pausa e evitar interromper são formas de demonstrar que há espaço para a história do outro.'),('Um convite para continuar','Perguntar se a pessoa gostaria de continuar a conversa, em outro momento, ajuda a manter a porta aberta. Escutar também envolve reconhecer nossos limites e respeitar a privacidade de quem fala.')]),
    dict(slug='familia-rede-de-apoio', title='Família: construindo uma rede de apoio, juntos', category='familia', tags=['apoio','dialogo'], image='family', date='2026-09-15', label='15 set. 2026', read='3 min', excerpt='Pequenos gestos de presença e diálogo podem abrir espaço para relações mais próximas.', sections=[('Apoio começa com uma conversa','Cada família tem sua história e sua maneira de se comunicar. Perguntar como alguém prefere receber ajuda é um ponto de partida para uma convivência mais atenta.'),('Dividir tarefas e expectativas','Combinar responsabilidades de forma clara evita que tudo fique concentrado em uma pessoa. Os acordos podem ser simples e revistos sempre que a rotina mudar.'),('Respeitar limites também é cuidar','Oferecer companhia não significa decidir pelo outro. Ouvir suas preferências e reconhecer o espaço de cada pessoa faz parte de uma relação de respeito.')]),
    dict(slug='pausas-no-dia-a-dia', title='Pequenas pausas, mais presença no dia a dia', category='bem-estar', tags=['rotina','escuta'], image='nature', date='2026-09-12', label='12 set. 2026', read='3 min', excerpt='Um convite para desacelerar e perceber os momentos simples que fazem parte da sua rotina.', sections=[('Perceber o próprio ritmo','Entre compromissos e tarefas, às vezes seguimos o dia sem observar como estamos. Uma pausa pode ser apenas um momento para olhar ao redor e reconhecer o que pede atenção.'),('Encontrar espaço no cotidiano','Tomar um café sem olhar a tela ou caminhar por alguns minutos são possibilidades, quando cabem na rotina. Não existe um único jeito de aproveitar uma pausa.'),('Começar de forma simples','Escolha um momento possível, sem transformar a pausa em mais uma obrigação. Observar o que funciona para você é mais útil do que seguir uma rotina rígida.')]),
    dict(slug='primeiro-contato', title='O que esperar de uma primeira conversa com nossa equipe', category='acolhimento', tags=['escuta','apoio'], image='space', date='2026-09-09', label='9 set. 2026', read='4 min', excerpt='Conheça a proposta de um contato conduzido com atenção, clareza e respeito ao seu momento.', sections=[('Um espaço para suas perguntas','O primeiro contato é uma oportunidade para apresentar dúvidas e conhecer a proposta de atendimento. Você pode compartilhar o que considera importante, no seu tempo.'),('Informações com clareza','Antes de tomar uma decisão, vale pedir explicações sobre as etapas, horários e formas de contato. Uma conversa clara ajuda a alinhar expectativas.'),('O próximo passo pode ser combinado','Ao final, você pode perguntar quais são as possibilidades de continuidade. O objetivo é compreender as informações e decidir com tranquilidade.')]),
    dict(slug='dialogo-em-familia', title='Como abrir espaço para o diálogo em família', category='familia', tags=['dialogo','escuta'], image='hero', date='2026-09-06', label='6 set. 2026', read='3 min', excerpt='Conversas com menos interrupções e mais curiosidade sobre o que o outro tem a dizer.', sections=[('Escolher um momento possível','Um assunto importante merece um momento em que as pessoas possam prestar atenção. Perguntar se é uma boa hora para conversar é um gesto simples de consideração.'),('Falar da própria experiência','Descrever o que você percebe e sente pode ajudar a explicar seu ponto de vista. Dar espaço para diferentes perspectivas faz parte da conversa.'),('Retomar quando for necessário','Nem todo assunto precisa se resolver de uma vez. Se a conversa ficar difícil, é possível combinar uma pausa e um momento para retomá-la.')]),
    dict(slug='convivencia-e-presenca', title='O valor da convivência e dos encontros simples', category='bem-estar', tags=['apoio','rotina'], image='group', date='2026-09-03', label='3 set. 2026', read='3 min', excerpt='Estar junto pode começar com um convite, uma caminhada ou uma conversa sem pressa.', sections=[('Encontros que cabem na vida real','Uma conversa breve pode ter valor mesmo em uma semana cheia. O importante é que o encontro respeite a disponibilidade e a vontade de quem participa.'),('Interesses em comum','Compartilhar uma atividade pode ser uma forma natural de passar tempo junto. Uma leitura, uma caminhada ou uma refeição oferecem oportunidades para trocar experiências.'),('Espaço para diferentes jeitos de estar','Algumas pessoas gostam de grupos; outras preferem encontros mais reservados. Considerar essas diferenças torna os convites mais acolhedores.')]),
    dict(slug='cuidado-nos-detalhes', title='O acolhimento também mora nos pequenos detalhes', category='acolhimento', tags=['escuta','apoio'], image='team', date='2026-08-28', label='28 ago. 2026', read='4 min', excerpt='Uma apresentação cuidadosa e informações claras fazem parte de uma recepção atenta.', sections=[('Receber com atenção','Apresentar-se e explicar como a conversa vai acontecer são gestos que ajudam a orientar quem chega. Pequenos detalhes comunicam disponibilidade.'),('Perguntar em vez de presumir','Cada pessoa traz preferências e necessidades diferentes. Perguntar como ela gostaria de ser chamada ou se precisa de alguma informação evita suposições.'),('Manter a comunicação acessível','Usar palavras claras e abrir espaço para dúvidas ajuda a construir entendimento. Quando algo não ficou claro, explicar de outra maneira pode fazer diferença.')]),
    dict(slug='compartilhar-o-cotidiano', title='Compartilhar o cotidiano, respeitando a individualidade', category='familia', tags=['rotina','dialogo'], image='family', date='2026-08-24', label='24 ago. 2026', read='3 min', excerpt='Como pensar em acordos de convivência que considerem o espaço e o tempo de cada pessoa.', sections=[('Uma casa, diferentes rotinas','Horários, preferências e compromissos nem sempre coincidem. Conversar sobre essas diferenças ajuda a construir acordos que façam sentido para todos.'),('Acordos podem mudar','O que funcionou em um momento pode precisar de ajustes depois. Reservar um tempo para rever combinações permite acompanhar as mudanças do cotidiano.'),('Individualidade e companhia','Ter momentos próprios e compartilhar atividades são possibilidades que podem coexistir. O equilíbrio depende do diálogo e das preferências de cada família.')]),
]

def cat_url(slug): return 'categoria.html' if slug == 'familia' else f'categoria-{slug}.html'
def tag_url(slug): return 'tag.html' if slug == 'escuta' else f'tag-{slug}.html'
def post_url(post): return 'post.html' if post == POSTS[0] else f'post-{post["slug"]}.html'
for post in POSTS:
    post['url'] = post_url(post)
    post['categoryLabel'] = CATEGORIES[post['category']]
    post['categoryUrl'] = cat_url(post['category'])

def button(text='Fale pelo WhatsApp', style='', url=WA):
    ext = ' target="_blank" rel="noopener noreferrer"' if url.startswith('https:') else ''
    return f'<a class="button {style}" href="{url}"{ext}>{text}{ARROW}</a>'

def brand():
    return '<a class="brand" href="index.html" aria-label="Renova Vida — início"><img src="assets/images/logo.png" width="48" height="48" alt=""><span class="brand-name">Renova Vida<small>M&amp;F · Acolher e orientar</small></span></a>'

def header(active=''):
    return f'''<a class="skip" href="#conteudo">Pular para o conteúdo</a>
<header class="site-header"><div class="container header-inner">{brand()}
<nav class="nav" id="menu-principal" aria-label="Navegação principal">
<a href="index.html#como-funciona">Como funciona</a><a href="index.html#beneficios">Benefícios</a><a href="index.html#familia">Família</a><a href="index.html#faq">Dúvidas</a><a href="blog.html" {'aria-current="page"' if active == 'blog' else ''}>Blog</a></nav>
<a class="button outline header-cta" href="{WA}" target="_blank" rel="noopener noreferrer">FALAR AGORA {ARROW}</a>
<button class="menu-toggle" aria-label="Abrir menu" aria-expanded="false" aria-controls="menu-principal"><span></span><span></span></button></div></header>'''

def footer():
    return f'''<footer class="site-footer"><div class="container"><div class="footer-top"><div class="footer-about">{brand()}<p>Escutar com atenção. Orientar com respeito.<br>Atendimento humanizado para você e sua família.</p><p>CNPJ: 66.758.501/0001-40</p></div>
<div class="footer-nav"><div><strong>Explore</strong><a href="pagina.html">Nossa essência</a><a href="index.html#como-funciona">Como funciona</a><a href="index.html#familia">Apoio à família</a><a href="blog.html">Conteúdos e orientações</a><a href="index.html#faq">Perguntas frequentes</a></div><div><strong>Vamos conversar</strong><a href="{WA}" target="_blank" rel="noopener noreferrer">WhatsApp · (61) 9156-5342</a><a href="tel:08009930103">Central · 0800 993 0103</a><a href="mailto:contato@mefrenovavida.com.br">contato@mefrenovavida.com.br</a><a href="index.html#contato">Seg. a sex., das 08h às 18h</a></div></div></div>
<div class="footer-bottom"><span>© 2026 M&amp;F Renova Vida. Todos os direitos reservados.</span><span><a href="privacidade.html">Privacidade</a> &nbsp;·&nbsp; <a href="termos.html">Termos de uso</a> &nbsp;·&nbsp; <a href="cookies.html">Cookies</a></span></div></div></footer>
<a class="floating-contact" href="{WA}" target="_blank" rel="noopener noreferrer" aria-label="Conversar pelo WhatsApp (abre em nova aba)">{CHAT}</a>'''

def write(name, title, body, active='', description='Atendimento humanizado, orientação personalizada e apoio para você e sua família. M&F Renova Vida.'):
    page_url = SITE_URL + ('' if name == 'index.html' else name)
    social_title = escape(title + ' | Renova Vida', quote=True)
    social_description = escape(description, quote=True)
    page_type = 'article' if any(post['url'] == name for post in POSTS) else 'website'
    html = f'''<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{escape(title)} | Renova Vida</title>
<meta name="description" content="{escape(description, quote=True)}"><meta name="robots" content="noindex, nofollow"><meta name="theme-color" content="#fffefa">
<link rel="canonical" href="{page_url}">
<meta property="og:locale" content="pt_BR">
<meta property="og:site_name" content="M&amp;F Renova Vida">
<meta property="og:type" content="{page_type}">
<meta property="og:title" content="{social_title}">
<meta property="og:description" content="{social_description}">
<meta property="og:url" content="{page_url}">
<meta property="og:image" content="{OG_IMAGE}">
<meta property="og:image:secure_url" content="{OG_IMAGE}">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="M&amp;F Renova Vida — logotipo dourado sobre fundo preto">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{social_title}">
<meta name="twitter:description" content="{social_description}">
<meta name="twitter:image" content="{OG_IMAGE}">
<meta name="twitter:image:alt" content="M&amp;F Renova Vida — logotipo dourado sobre fundo preto">
<link rel="icon" type="image/png" href="assets/images/logo.png"><link rel="preload" href="assets/fonts/cormorant.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="assets/fonts/inter.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="assets/css/styles.css"><script src="assets/js/posts.js" defer></script><script src="assets/js/main.js" defer></script></head>
<body>{header(active)}<main id="conteudo">{body}</main>{footer()}</body></html>'''
    (ROOT / name).write_text(html, encoding='utf-8')

def card(post):
    return f'''<article class="post-card"><a class="post-image" href="{post['url']}" tabindex="-1" aria-hidden="true"><img src="assets/images/{post['image']}.jpg" alt="" loading="lazy" width="600" height="400"></a><div class="post-meta"><a class="post-category" href="{post['categoryUrl']}">{post['categoryLabel']}</a><time datetime="{post['date']}">{post['label']}</time></div><h3><a href="{post['url']}">{post['title']}</a></h3><p>{post['excerpt']}</p><a class="text-link" href="{post['url']}" aria-label="Ler artigo: {post['title']}">Ler artigo {ARROW}</a></article>'''

def demo_note(): return '<p class="demo-note">Prévia editorial: os artigos e as datas são demonstrativos, para apresentação do layout.</p>'
def cta():
    return f'''<section class="cta-section"><span class="eyebrow">Um novo capítulo</span><h2>O primeiro passo começa<br>com uma <em>conversa.</em></h2><p>Sem compromisso, sem pressa. Apenas escuta qualificada, respeito e orientação personalizada para o seu momento.</p>{button('Falar com nossa equipe')}<p class="micro">ATENDIMENTO RESERVADO · RESPEITO À SUA HISTÓRIA</p></section>'''

steps = [('Entre em contato','Uma conversa reservada pelo WhatsApp para entendermos como podemos ajudar.'),('Receba uma orientação','Nossa equipe escuta com atenção e oferece uma orientação para o seu momento.'),('Encontre seu caminho','Ajudamos você e sua família a conhecer as alternativas, com respeito e clareza.'),('Conte com nosso apoio','Um suporte próximo em todas as etapas, com escuta e acompanhamento.')]
benefits = [('♡','Atendimento humanizado','Uma equipe que escuta antes de tudo. Cada história recebe a atenção que merece.'),('◇','Cuidado personalizado','Cada orientação considera o seu momento, sem fórmulas prontas.'),('♧','Sigilo e privacidade','Discrição em cada contato, com respeito à sua história e à sua família.'),('✧','Equipe especializada','Profissionais preparados para oferecer suporte com respeito e clareza.'),('↔','Comunicação clara','Informações objetivas, sem pressa e sem pressão para decidir.'),('◎','Suporte próximo','Acompanhamento em todas as etapas, com escuta e apoio contínuo.')]
faqs = [('Como funciona o primeiro contato?','Basta enviar uma mensagem pelo WhatsApp. Nossa equipe responde com atenção e conduz a conversa com respeito, sem pressa e sem julgamentos.'),('Como posso falar com a equipe?','O canal principal é o WhatsApp. Você pode usar qualquer botão de contato desta página ou ligar para nossa central: 0800 993 0103.'),('O atendimento é sigiloso?','A discrição é um dos pilares do nosso trabalho. Todo contato e orientação são conduzidos com respeito à sua privacidade.'),('Como recebo orientação?','Depois do primeiro contato, nossa equipe oferece uma orientação personalizada, ajustada ao seu momento e às suas dúvidas.'),('Quais são os horários de atendimento?','Nossa equipe atende de segunda a sexta, das 08h às 18h. Você pode enviar uma mensagem pelo WhatsApp a qualquer momento; retornaremos assim que possível.'),('Posso entrar em contato apenas para tirar dúvidas?','Sim. Você pode nos chamar pelo WhatsApp para entender melhor o atendimento. Explicamos cada etapa com clareza, sem compromisso.')]

home = f'''<section class="hero"><div class="container"><div class="hero-title"><span class="eyebrow line">M&amp;F Renova Vida</span><h1>Um novo começo<br>pode começar <em>hoje.</em></h1></div><div class="hero-grid"><div class="hero-copy"><p>Nossa equipe oferece atendimento humanizado, orientação personalizada e suporte em cada etapa. Com respeito, discrição e cuidado com você e sua família.</p>{button()}<p class="micro">Atendimento rápido e reservado.</p><div class="trust"><span>Atendimento humanizado</span><span>Sigilo</span><span>Equipe especializada</span></div></div><div class="hero-photo"><img src="assets/images/hero.jpg" alt="Uma família em uma conversa acolhedora com uma profissional" width="1280" height="1600" fetchpriority="high"><div class="photo-badge"><strong>+15</strong><span>Anos de experiência</span></div><div class="quote-card"><span class="eyebrow line">Nossa essência</span><p>“Escutar com atenção,<br>orientar com respeito.”</p></div></div></div><div class="hero-end">Cuidado que começa na escuta</div></div></section>
<section class="section" id="como-funciona"><div class="container"><div class="section-head center"><span class="eyebrow">Como funciona</span><h2>Um processo simples,<br><em>passo a passo.</em></h2><p>Cada etapa é conduzida com escuta, respeito e discrição.<br>Você não precisa ter todas as respostas para começar.</p></div><img class="process-image" src="assets/images/space.jpg" alt="Família sendo recebida em um ambiente acolhedor" width="1400" height="1000" loading="lazy"><div class="steps">{''.join(f'<div><span class="step-number">0{i+1}</span><h3>{t}</h3><p>{d}</p></div>' for i,(t,d) in enumerate(steps))}</div><div class="center-action">{button('Iniciar minha conversa','outline')}</div></div></section>
<section class="section cream" id="beneficios"><div class="container benefit-layout"><div class="benefit-intro"><span class="eyebrow line">Benefícios</span><h2>O que faz a<br><em>diferença.</em></h2><p>Um atendimento pensado nos detalhes.<br>Porque é neles que a confiança se constrói.</p><img src="assets/images/hands.jpg" alt="Conversa individual com atenção e acolhimento" width="1200" height="1408" loading="lazy"></div><div class="benefit-grid">{''.join(f'<article class="benefit-card"><span class="icon-circle" aria-hidden="true">{icon}</span><h3>{t}</h3><p>{d}</p></article>' for icon,t,d in benefits)}</div></div></section>
<section class="section" id="diferenciais"><div class="container split"><div><span class="eyebrow line">Nossos diferenciais</span><h2>Um jeito mais<br><em>humano</em> de atender.</h2><ul class="check-list"><li>Acolhimento em todas as etapas</li><li>Respeito à sua história e à sua privacidade</li><li>Profissionais qualificados e preparados</li><li>Orientação personalizada ao seu momento</li><li>Suporte próximo às famílias</li><li>Compromisso com a qualidade do atendimento</li></ul>{button('Conheça nossa equipe')}</div><div class="split-image"><img src="assets/images/team.jpg" alt="Profissionais reunidos em uma conversa" width="1400" height="1000" loading="lazy"><div class="quote-card"><span class="eyebrow">Gente que cuida de gente</span><p>Uma equipe que escuta,<br>orienta e caminha com você.</p></div></div></div></section>
<section class="section pillars"><div class="container"><div class="section-head center"><span class="eyebrow">Nosso compromisso</span><h2>Três pilares.<br>Um mesmo <em>cuidado.</em></h2></div><div class="pillar-grid">{''.join(f'<article class="pillar"><span class="icon-circle" aria-hidden="true">{icon}</span><h3>{t}</h3><p>{d}</p></article>' for icon,t,d in [('♡','Atendimento humanizado','Escuta atenta e orientação em cada conversa, antes de qualquer decisão.'),('◇','Sigilo e respeito','Sua história é tratada com a discrição e o cuidado que merece.'),('✧','Compromisso com a qualidade','Profissionais qualificados e atenção em cada detalhe do atendimento.')])}</div></div></section>
<section class="section family" id="familia"><div class="container split"><div class="split-image family-photo"><img src="assets/images/family.jpg" alt="Família reunida em um abraço ao ar livre" width="1400" height="1000" loading="lazy"><img class="inset" src="assets/images/group.jpg" alt="Grupo compartilhando uma conversa no jardim" width="1400" height="1000" loading="lazy"></div><div><span class="eyebrow line">Família</span><h2>Apoio a você<br>e à sua <em>família.</em></h2><p>Cada história merece atenção, respeito e orientação adequada. Estamos aqui para acolher você e sua família, com um atendimento próximo, humano e personalizado.</p><blockquote>“Escuta atenta, respeito e orientação em cada conversa.”</blockquote>{button('Falar com nossa equipe','outline')}</div></div></section>
<section class="section cream" id="faq"><div class="container faq-layout"><div class="section-head"><span class="eyebrow line">Perguntas frequentes</span><h2>Antes de<br><em>começar.</em></h2><p>Algumas respostas para que você dê o primeiro passo com mais tranquilidade.</p></div><div class="faq-list">{''.join(f'<details {"open" if i == 0 else ""}><summary>{q}</summary><p>{a}</p></details>' for i,(q,a) in enumerate(faqs))}</div></div></section>
<section class="section" id="blog"><div class="container"><div class="head-row"><div class="section-head"><span class="eyebrow line">Nosso blog</span><h2>Conteúdos que acolhem.<br>Orientações que <em>aproximam.</em></h2></div><a class="text-link" href="blog.html">Ver todos os artigos {ARROW}</a></div><div class="post-grid">{''.join(card(p) for p in POSTS[:3])}</div>{demo_note()}</div></section>
{cta()}<section class="contact" id="contato"><div class="container contact-inner"><div><span class="eyebrow line">Estamos por perto</span><h2>Fale com <em>nossa equipe.</em></h2></div><div class="contact-links"><div><small>WhatsApp</small><a href="{WA}" target="_blank" rel="noopener noreferrer">(61) 9156-5342 {ARROW}</a></div><div><small>Central de atendimento</small><a href="tel:08009930103">0800 993 0103</a></div><div><small>Horário</small><p class="micro">Seg. a sex. · 08h às 18h</p></div></div></div></section>'''
write('index.html','Um novo começo pode começar hoje',home)

def breadcrumb(label):
    parent = '<span><a href="blog.html">Blog</a></span>' if label != 'Blog' else ''
    return f'<nav class="breadcrumb" aria-label="Você está aqui"><span><a href="index.html">Início</a></span>{parent}<span aria-current="page">{label}</span></nav>'
def search_form(): return f'<form class="search-form" action="busca.html" method="get" role="search"><label for="busca" class="sr-only">Buscar no blog</label><input id="busca" name="s" type="search" placeholder="O que você procura?" maxlength="150"><button type="submit" aria-label="Buscar">{SEARCH}</button></form>'
def filters(selected=''): return '<nav class="filters" aria-label="Categorias do blog">' + f'<a class="filter {"active" if not selected else ""}" href="blog.html">Todos os artigos</a>' + ''.join(f'<a class="filter {"active" if k == selected else ""}" href="{cat_url(k)}" {"aria-current=page" if k == selected else ""}>{v}</a>' for k,v in CATEGORIES.items()) + '</nav>'

def listing(name, title, heading, intro, kind='all', value='', posts=None):
    selected = POSTS if posts is None else posts
    label = 'Conteúdos e orientações' if kind == 'all' else ('Categoria' if kind == 'category' else ('Tag' if kind == 'tag' else 'Busca'))
    grid = ''.join(card(p) for p in selected[:6])
    start = '<div class="empty-state"><h2>O que você gostaria de encontrar?</h2><p>Busque por um assunto, como família, escuta ou acolhimento.</p></div>' if kind == 'search' else grid
    body = f'''<section class="page-heading"><div class="container">{breadcrumb(title)}<span class="eyebrow line">{label}</span><h1 id="listing-title">{heading}</h1><p>{intro}</p></div></section><section class="listing-section"><div class="container" data-listing="{kind}" data-value="{value}"><div class="blog-controls">{filters(value if kind == 'category' else '')}{search_form()}</div><p class="result-count" id="result-count" role="status">{f'{len(selected)} artigos demonstrativos' if kind != 'search' else 'Digite um termo para buscar nos artigos.'}</p><div id="post-results" class="{'post-grid' if kind != 'search' else ''}">{start}</div><nav class="pagination" id="pagination" aria-label="Paginação dos artigos"></nav><noscript><p>A busca e a paginação interativa precisam de JavaScript. Você pode navegar pelos artigos disponíveis em cada categoria.</p></noscript>{demo_note()}</div></section>{cta()}'''
    write(name,title,body,'blog',intro)

listing('blog.html','Blog','Um espaço para<br><em>acolher e compartilhar.</em>','Reflexões sobre cuidado, família e bem-estar. Leituras para acompanhar você, no seu tempo.')
for slug, label in CATEGORIES.items():
    listing(cat_url(slug),label,f'{label}<em>.</em>',{'familia':'Diálogo, presença e apoio. Conteúdos para caminhar mais perto de quem faz parte da sua história.','acolhimento':'O cuidado começa na escuta. Reflexões sobre presença, respeito e atenção a cada história.','bem-estar':'Um olhar atento para a rotina, os encontros e os pequenos momentos do cotidiano.'}[slug],'category',slug,[p for p in POSTS if p['category'] == slug])
for slug,label in TAGS.items():
    listing(tag_url(slug),label,f'Conversas sobre <em>{label.lower()}.</em>',f'Explore os artigos reunidos pelo tema {label.lower()}.','tag',slug,[p for p in POSTS if slug in p['tags']])
listing('busca.html','Busca','Encontre sua<br>próxima <em>leitura.</em>','Busque conteúdos por título, assunto ou palavra-chave.','search',posts=[])

for post in POSTS:
    related = sorted([p for p in POSTS if p != post], key=lambda p:p['category'] != post['category'])[:3]
    body=f'''<div class="container"><header class="article-header">{breadcrumb(post['categoryLabel'])}<a class="eyebrow line" href="{post['categoryUrl']}">{post['categoryLabel']}</a><h1>{post['title']}</h1><div class="article-byline"><span>Redação Renova Vida · Exemplo editorial</span><time datetime="{post['date']}">{post['label']}</time><span>{post['read']} de leitura</span></div></header><img class="article-cover" src="assets/images/{post['image']}.jpg" alt="" width="1400" height="900" fetchpriority="high"><div class="article-layout"><article class="article-body" aria-label="Conteúdo do artigo"><div class="article-notice">Artigo demonstrativo para apresentação do layout. Conteúdo e data sujeitos à revisão editorial antes da publicação.</div><p class="lead">{post['excerpt']}</p>{''.join(f'<h2>{title}</h2><p>{text}</p>' for title,text in post['sections'])}<blockquote>“Escutar com atenção, orientar com respeito.”</blockquote><nav class="tags" aria-label="Temas deste artigo">{''.join(f'<a class="filter" href="{tag_url(tag)}">#{TAGS[tag].lower()}</a>' for tag in post['tags'])}</nav><div class="center-action"><a class="text-link" href="blog.html">← Voltar para o blog</a></div></article><aside class="article-sidebar"><span class="eyebrow">Conte com a gente</span><h3>Uma conversa pode ser o <em>começo.</em></h3><p>Nossa equipe está aqui para ouvir suas dúvidas e orientar com respeito.</p>{button('Vamos conversar')}</aside></div></div><section class="section cream related"><div class="container"><div class="head-row"><div class="section-head"><span class="eyebrow line">Continue a leitura</span><h2>Outras histórias.<br>Novos <em>olhares.</em></h2></div><a class="text-link" href="blog.html">Todos os artigos {ARROW}</a></div><div class="post-grid">{''.join(card(p) for p in related)}</div></div></section>'''
    write(post['url'],post['title'],body,'blog',post['excerpt'])

write('404.html','Página não encontrada',f'''<section class="not-found"><div class="container"><span class="eyebrow">Um pequeno desvio no caminho</span><div class="error-number" aria-hidden="true">404</div><h1>Vamos encontrar<br>um novo <em>caminho?</em></h1><p>A página que você procura não foi encontrada. Mas há outros caminhos para continuar por aqui.</p>{button('Voltar ao início',url='index.html')}{button('Conhecer o blog','outline','blog.html')}{search_form()}</div></section>''')

page_body = f'''<section class="page-heading"><div class="container"><nav class="breadcrumb" aria-label="Você está aqui"><span><a href="index.html">Início</a></span><span aria-current="page">Nossa essência</span></nav><span class="eyebrow line">M&amp;F Renova Vida</span><h1>Cuidar começa<br>por <em>escutar.</em></h1><p>Uma forma próxima e humana de acolher cada história.</p></div></section><div class="container legal"><h2>Respeito em cada conversa</h2><p>Nossa proposta é oferecer atendimento humanizado, orientação personalizada e suporte durante todo o processo, com respeito, discrição e compromisso com cada pessoa e sua família.</p><h2>Você e sua família</h2><p>Cada história merece atenção. Nossa equipe está preparada para ouvir suas dúvidas e apresentar as etapas do atendimento com clareza.</p><h2>Vamos conversar?</h2><p>O atendimento acontece de segunda a sexta, das 08h às 18h. Você pode enviar uma mensagem pelo WhatsApp e nossa equipe retornará assim que possível.</p>{button()}</div>'''
write('pagina.html','Nossa essência',page_body)

for filename,title,sections in [
    ('privacidade.html','Política de Privacidade',[('Documento em preparação','Esta página demonstra a apresentação visual da Política de Privacidade. A versão definitiva deverá descrever o tratamento de dados realizado na operação do site e seus canais de contato.'),('Contato','Para falar com a equipe, utilize o e-mail contato@mefrenovavida.com.br.')]),
    ('termos.html','Termos de Uso',[('Documento em preparação','Esta página está reservada para os Termos de Uso do site. O texto definitivo deverá ser revisado e aprovado pela organização antes da publicação.'),('Sobre este protótipo','Os artigos do blog e suas datas são exemplos editoriais usados para demonstrar a navegação e o layout.')]),
    ('cookies.html','Política de Cookies',[('Sobre esta demonstração','O protótipo não inclui ferramentas de análise, publicidade ou cookies próprios. As fontes e imagens são carregadas da pasta local de arquivos.'),('Versão definitiva','Esta página deverá ser atualizada de acordo com as ferramentas efetivamente utilizadas no site publicado. Links de contato podem levar a serviços externos, como o WhatsApp.')]),
]:
    write(filename,title,f'<section class="page-heading"><div class="container"><nav class="breadcrumb" aria-label="Você está aqui"><span><a href="index.html">Início</a></span><span aria-current="page">{title}</span></nav><span class="eyebrow line">Informações institucionais</span><h1>{title}</h1></div></section><div class="container legal"><div class="article-notice">Modelo visual — documento ainda não publicado como política definitiva.</div>'+''.join(f'<h2>{h}</h2><p>{p}</p>' for h,p in sections)+'</div>')

(ROOT/'assets/js').mkdir(parents=True,exist_ok=True)
(ROOT/'assets/js/posts.js').write_text('/* Conteúdo demonstrativo; substituir por consultas do WordPress na integração. */\nwindow.RENOVA_POSTS = '+json.dumps(POSTS,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print(f'Protótipo gerado em {ROOT}: {len(list(ROOT.glob("*.html")))} páginas HTML.')
